version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: my_api
    restart: always
    env_file:
      - .env
    volumes:
      - ./app:/gwt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: